import Headers from "@/app/Header/Headers";
import "./globals.css";

import Headerbt from "./Headerbottom/Headerbt";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Headers />
        <Headerbt />
        {children}
      </body>
    </html>
  );
}
